root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  full_bin = "./tmp/api"
  include_ext = ["go"]
  include_dir = ["cmd", "internal"]
  exclude_dir = ["tmp", "vendor", "testdata", "flutter_app", "seed"]
  exclude_regex = ["_test\\.go$"]
  delay = 1000
  stop_on_error = true
  log = "air.log"
  poll = false
  poll_interval = 0

[log]
  time = false
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
